version: '3.8'
services:
  app:
    container_name: nestjs_vehicle_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=vehicle_db
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - vehicle-network

  mysql:
    container_name: mysql_vehicle_db
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vehicle_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - vehicle-network

networks:
  vehicle-network:
    driver: bridge

volumes:
  mysql_data:
